
###
GET http://localhost:5000/heroku



GET http://localhost:5000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJuYW1lIjoic2IiLCJwcm9maWxlIjoiIiwidXNlcm5hbWUiOiJzdWx0aGFuIiwicGFzc3dvcmQiOiIkMmIkMTAkenY1Lk5xQ1JhZTZtQ2ExOVNxZWhoLnB1MHdzQ1ZGSWJxeWNoLzNBM25WbVFKVmVGdUJYUHUiLCJpYXQiOjE2NTUxODI0OTd9.X-d0g3phmrw-4DmGWVl9lygNjfJlva2v-vdCr6bC-LA

###


POST http://localhost:5000/login
Content-Type: application/json

{
    "password": "sulthan",
    "username": "sulthan"
}


###



POST http://localhost:5000/users/new 
Content-Type: application/json

{
    "name": "sb",
    "password": "sulthan",
    "username": "sulthan",
     "profile": ""
}


###



GET http://localhost:5000/rooms/1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJuYW1lIjoic2IiLCJwcm9maWxlIjoiIiwidXNlcm5hbWUiOiJzdWx0aGFuIiwicGFzc3dvcmQiOiIkMmIkMTAkenY1Lk5xQ1JhZTZtQ2ExOVNxZWhoLnB1MHdzQ1ZGSWJxeWNoLzNBM25WbVFKVmVGdUJYUHUiLCJpYXQiOjE2NTUxODI0OTd9.X-d0g3phmrw-4DmGWVl9lygNjfJlva2v-vdCr6bC-LA

###



POST http://localhost:5000/rooms/1/messages/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJuYW1lIjoic2IiLCJwcm9maWxlIjoiIiwidXNlcm5hbWUiOiJzdWx0aGFuIiwicGFzc3dvcmQiOiIkMmIkMTAkenY1Lk5xQ1JhZTZtQ2ExOVNxZWhoLnB1MHdzQ1ZGSWJxeWNoLzNBM25WbVFKVmVGdUJYUHUiLCJpYXQiOjE2NTUxODI0OTd9.X-d0g3phmrw-4DmGWVl9lygNjfJlva2v-vdCr6bC-LA

{
    "message": "youth pp7 from sb new"
}


